### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by jooblex** [Dmitry-407/nmap#4]
Было нечего делать, перевёл на английский

**Comment by jooblex** [comment]
Вызывает кучу ошибок, что с ними делать?

**Comment by DimaPopov** [comment]
Спасибо за вклад в развитие расширения!

Пожалуйста, внесите эти изменения через пулреквест, так я смогу наглядно показать из-за чего возникают ошибки и как их исправить.

**Comment by jooblex** [comment]
Извини, это был поспешный перевод за 1 день, сейчас буду делать нормальный

**Comment by jooblex** [comment]
Не хочешь, как желаешь

**Comment by DimaPopov** [comment]
Пожалуйста, создайте pull request. Отправка изменений через GitHub в виде zip архива это что-то интересное 🤣

**Comment by jooblex** [comment]
> Пожалуйста, создайте pull request. Отправка изменений через GitHub в виде zip архива это что-то интересное 🤣

А можно понятно объяснить, а не надсмехаться? Разве похоже что я не первый день на github?

**Comment by DimaPopov** [comment]
Не было и в мыслях надсмехаться. 

Чтобы создать Pull Request нужно создать форк (кнопка в правом верхнем углу)
![image](https://user-images.githubusercontent.com/52531675/225994671-3172c64e-34ea-4584-8cb6-046d275ae4e3.png)

Затем есть два варианта: внести изменения в каждый файл через веб-версию редактора или скачать [GitHub Desktop](https://desktop.github.com/), затем скачать себе копию форка и внести изменения путем замены файлов в каталоге и затем отправить изменения в форк. 

После того как ты внесешь изменения в форке, на странице репозитория https://github.com/Dmitry-407/nmap появится кнопка **Create Pull Request**.

**Comment by jooblex** [comment]
Блин, надо было мне сразу через pull request переводить.

**Comment by n1rwana** [comment]
@Dmitry-407 как вам не стыдно насмехаться над пользователями расширения?
