### ISSUE TITLE
Ошибка в переводе

### ISSUE THREAD

**Issue by coteyka1209** [Dmitry-407/nmap#7]
![image](https://github.com/BoxDmitry/nmap/assets/132197512/f721db8f-a00e-4391-bdb4-dc96329d4763)
В настройках расширения, вкладка **модули**. Картографичяеский сервис :D

**Comment by DimaPopov** [comment]
Опечатки в коде нет, она была исправлена @m90tass в #5 после последнего релиза.

**Comment by DimaPopov** [comment]
📦 Опубликована версия [5.0.1](https://github.com/BoxDmitry/nmap/releases/tag/v5.0.1) в которой эта опечатка исправлена
