### ISSUE TITLE
Неправильное отображение заголовка кнопки.

### ISSUE THREAD

**Issue by coteyka1209** [Dmitry-407/nmap#8]
Если в настройках расширения, в модулях включить "Переход на другие картографические сервисы", а потом навести курсор на кнопку сторонних карт, заголовок появиться снизу, что делает его невозможным к прочтению
![image](https://github.com/BoxDmitry/nmap/assets/132197512/8415123c-831b-4ef8-b2ca-2a01e8fd5ec9)

Незначительный баг, но выглядит неэстетично

**Comment by DimaPopov** [comment]
📦 Опубликована версия [5.0.1](https://github.com/BoxDmitry/nmap/releases/tag/v5.0.1) в которой исправлена эта проблема
