### ISSUE TITLE
Не удалось получить информацию от Фонда реновации

### ISSUE THREAD

**Issue by StudioMaX** [Dmitry-407/nmap#9]
В последнем обновлении появилась некая погрузка данных Фонда реновации. В настройках расширения этот модуль вообще отключен, с ним не было никакого взаимодействия, но в некоторые фантомные моменты регулярно появляется ошибка "Не удалось получить информацию от Фонда реновации". Возможно где-то отсутствует проверка что этот модуль отключен, предположительно при открытии свойств зданий после каких-то событий.
![image](https://github.com/user-attachments/assets/79adce62-3b36-44d7-9a10-37807edcada6)

**Comment by DimaPopov** [comment]
Здравствуйте!

Подскажите, пожалуйста, сообщение, появляется при взаимодействии со зданиями или при загрузке Народной карты?

**Comment by StudioMaX** [comment]
Как я понимаю при взаимодействии с адресами. Судя по консоли изначально вызывается отсюда без дополнительных проверок что модуль включен
https://github.com/DimaPopov/nmap/blob/0142939f3f336381bfd5a98a8969234ac033a760/resources/module/object/address.js#L105
И затем через несколько попыток поиска блока(?) отображается уже сама ошибка
https://github.com/DimaPopov/nmap/blob/0142939f3f336381bfd5a98a8969234ac033a760/resources/fr.mos.ru.js#L75-L81

**Comment by DimaPopov** [comment]
Решено в версии 5.1.1
